;; -*- lexical-binding: t; -*-

(TeX-add-style-hook
 "PTfonts"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "12pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "a3paper" "margin=1.5cm") ("fontspec" "") ("polyglossia" "") ("metalogo" "") ("relsize" "") ("hyperref" "verbose") ("graphicx" "") ("url" "") ("expex" "")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "glyphs/t01_glyphs"
    "glyphs/t01_glyphids"
    "glyphs/t02_glyphs"
    "glyphs/t02_glyphids"
    "glyphs/t03_glyphs"
    "glyphs/t03_glyphids"
    "glyphs/t04_glyphs"
    "glyphs/t04_glyphids"
    "glyphs/t05_glyphs"
    "glyphs/t05_glyphids"
    "glyphs/t06_glyphs"
    "glyphs/t06_glyphids"
    "glyphs/t07_glyphs"
    "glyphs/t07_glyphids"
    "glyphs/t08_glyphs"
    "glyphs/t08_glyphids"
    "glyphs/t09_glyphs"
    "glyphs/t09_glyphids"
    "glyphs/t10_glyphs"
    "glyphs/t10_glyphids"
    "glyphs/t11_glyphs"
    "glyphs/t11_glyphids"
    "glyphs/t12_glyphs"
    "glyphs/t12_glyphids"
    "glyphs/t13_glyphs"
    "glyphs/t13_glyphids"
    "glyphs/t14_glyphs"
    "glyphs/t14_glyphids"
    "glyphs/t15_glyphs"
    "glyphs/t15_glyphids"
    "glyphs/t16_glyphs"
    "glyphs/t16_glyphids"
    "glyphs/t17_glyphs"
    "glyphs/t17_glyphids"
    "glyphs/t18_glyphs"
    "glyphs/t18_glyphids"
    "glyphs/t19_glyphs"
    "glyphs/t19_glyphids"
    "glyphs/t20_glyphs"
    "glyphs/t20_glyphids"
    "glyphs/t21_glyphs"
    "glyphs/t21_glyphids"
    "glyphs/t22_glyphs"
    "glyphs/t22_glyphids"
    "glyphs/t23_glyphs"
    "glyphs/t23_glyphids"
    "glyphs/t24_glyphs"
    "glyphs/t24_glyphids"
    "glyphs/t25_glyphs"
    "glyphs/t25_glyphids"
    "glyphs/t26_glyphs"
    "glyphs/t26_glyphids"
    "glyphs/t27_glyphs"
    "glyphs/t27_glyphids"
    "glyphs/t28_glyphs"
    "glyphs/t28_glyphids"
    "glyphs/t29_glyphs"
    "glyphs/t29_glyphids"
    "glyphs/t30_glyphs"
    "glyphs/t30_glyphids"
    "glyphs/t31_glyphs"
    "glyphs/t31_glyphids"
    "glyphs/t32_glyphs"
    "glyphs/t32_glyphids"
    "glyphs/t33_glyphs"
    "glyphs/t33_glyphids"
    "glyphs/t34_glyphs"
    "glyphs/t34_glyphids"
    "glyphs/t35_glyphs"
    "glyphs/t35_glyphids"
    "glyphs/t36_glyphs"
    "glyphs/t36_glyphids"
    "glyphs/t37_glyphs"
    "glyphs/t37_glyphids"
    "glyphs/t38_glyphs"
    "glyphs/t38_glyphids"
    "glyphs/t39_glyphs"
    "glyphs/t39_glyphids"
    "glyphs/t40_glyphs"
    "glyphs/t40_glyphids"
    "glyphs/t41_glyphs"
    "glyphs/t41_glyphids"
    "glyphs/t42_glyphs"
    "glyphs/t42_glyphids"
    "glyphs/t43_glyphs"
    "glyphs/t43_glyphids"
    "glyphs/t44_glyphs"
    "glyphs/t44_glyphids"
    "glyphs/t45_glyphs"
    "glyphs/t45_glyphids"
    "glyphs/t46_glyphs"
    "glyphs/t46_glyphids"
    "glyphs/t47_glyphs"
    "glyphs/t47_glyphids"
    "glyphs/t48_glyphs"
    "glyphs/t48_glyphids"
    "glyphs/t49_glyphs"
    "glyphs/t49_glyphids"
    "glyphs/t50_glyphs"
    "glyphs/t50_glyphids"
    "glyphs/t51_glyphs"
    "glyphs/t51_glyphids"
    "glyphs/t52_glyphs"
    "glyphs/t52_glyphids"
    "glyphs/t53_glyphs"
    "glyphs/t53_glyphids"
    "glyphs/t54_glyphs"
    "glyphs/t54_glyphids"
    "glyphs/t55_glyphs"
    "glyphs/t55_glyphids"
    "glyphs/t56_glyphs"
    "glyphs/t56_glyphids"
    "glyphs/t57_glyphs"
    "glyphs/t57_glyphids"
    "glyphs/t58_glyphs"
    "glyphs/t58_glyphids"
    "glyphs/t59_glyphs"
    "glyphs/t59_glyphids"
    "glyphs/t60_glyphs"
    "glyphs/t60_glyphids"
    "glyphs/t61_glyphs"
    "glyphs/t61_glyphids"
    "glyphs/t62_glyphs"
    "glyphs/t62_glyphids"
    "glyphs/t63_glyphs"
    "glyphs/t63_glyphids"
    "glyphs/t64_glyphs"
    "glyphs/t64_glyphids"
    "glyphs/t65_glyphs"
    "glyphs/t65_glyphids"
    "glyphs/t66_glyphs"
    "glyphs/t66_glyphids"
    "glyphs/t67_glyphs"
    "glyphs/t67_glyphids"
    "glyphs/t68_glyphs"
    "glyphs/t68_glyphids"
    "glyphs/t69_glyphs"
    "glyphs/t69_glyphids"
    "glyphs/t70_glyphs"
    "glyphs/t70_glyphids"
    "glyphs/t71_glyphs"
    "glyphs/t71_glyphids"
    "glyphs/t72_glyphs"
    "glyphs/t72_glyphids"
    "glyphs/t73_glyphs"
    "glyphs/t73_glyphids"
    "glyphs/t74_glyphs"
    "glyphs/t74_glyphids"
    "glyphs/t75_glyphs"
    "glyphs/t75_glyphids"
    "glyphs/t76_glyphs"
    "glyphs/t76_glyphids"
    "glyphs/t77_glyphs"
    "glyphs/t77_glyphids"
    "glyphs/t78_glyphs"
    "glyphs/t78_glyphids"
    "glyphs/t79_glyphs"
    "glyphs/t79_glyphids"
    "glyphs/t80_glyphs"
    "glyphs/t80_glyphids"
    "glyphs/t81_glyphs"
    "glyphs/t81_glyphids"
    "glyphs/t82_glyphs"
    "glyphs/t82_glyphids"
    "glyphs/t83_glyphs"
    "glyphs/t83_glyphids"
    "glyphs/t84_glyphs"
    "glyphs/t84_glyphids"
    "glyphs/t85_glyphs"
    "glyphs/t85_glyphids"
    "glyphs/t86_glyphs"
    "glyphs/t86_glyphids"
    "glyphs/t87_glyphs"
    "glyphs/t87_glyphids"
    "glyphs/t88_glyphs"
    "glyphs/t88_glyphids"
    "glyphs/t89_glyphs"
    "glyphs/t89_glyphids"
    "article"
    "art12"
    "geometry"
    "fontspec"
    "polyglossia"
    "metalogo"
    "relsize"
    "hyperref"
    "graphicx"
    "url"
    "expex")
   (TeX-add-symbols
    '("examplePageEN" 1)
    '("examplePage" 1)
    '("exampleRef" 1)
    '("fontstat" 1)
    '("fontID" 2)
    '("exampleEN" 1)
    '("examplePL" 1)
    '("exampleLib" 1)
    '("exampleDig" 1)
    '("exampleDesc" 1)
    '("exampleBibExtra" 1)
    '("exampleBib" 1)
    '("plate" 3)
    '("pismoEN" 1)
    '("pismoPL" 1)
    '("PTglyphid" 1)
    '("PTglyph" 2)
    "bg"
    "alfa"
    "Hb")
   (LaTeX-add-labels
    "sec:introduction"
    "sec:catalogus-librorum"
    "sec:haebl-font-class"
    "sec:wierzb-bibl"
    "sec:estr-bibl"
    "sec:other-abbreviations"
    "sec:font-tables")
   (LaTeX-add-polyglossia-langs
    '("english" "mainlanguage" "")
    '("polish" "otherlanguage" "")))
 :latex)

