name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'typoglyphs.csv'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: 🔍 List site contents
        run: ls -alh site

      - name: 🔍 Find symlinks
        run: find site -type l

      - name: 📆 Upload artifact (Pages-compatible)
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
